export default Transactions = [
  {
    title: '10 03 2021',
    data: [
      {
        id: 1,
        name: 'PAP Transferred Money',
        delivery_fee: -1000,
        other_fee: -1000,
        taxi_commission_fee: 0,
        type: 'payment',
        from_id: 1,
        amount: -10000,
        time: '11:21',
      },
      {
        id: 2,
        name: 'PAP Received PK16',
        delivery_fee: 1000,
        other_fee: 1000,
        taxi_commission_fee: 1000,
        type: 'package',
        from_id: 1,
        amount: 10000,
        time: '10:38',
      },
    ],
  },
  {
    title: '11 07 2021',
    data: [
      {
        id: 1,
        name: 'PAP Transferred Money',
        delivery_fee: -1000,
        other_fee: -1000,
        taxi_commission_fee: 0,
        type: 'payment',
        from_id: 1,
        amount: -10000,
        time: '11:21',
      },
      {
        id: 2,
        name: 'PAP Received PK16',
        delivery_fee: 1000,
        other_fee: 1000,
        taxi_commission_fee: 1000,
        type: 'package',
        from_id: 1,
        amount: 10000,
        time: '10:38',
      },
    ],
  },
  {
    title: '10 03 2021',
    data: [
      {
        id: 1,
        name: 'PAP Transferred Money',
        delivery_fee: -1000,
        other_fee: -1000,
        taxi_commission_fee: 0,
        type: 'payment',
        from_id: 1,
        amount: -10000,
        time: '11:21',
      },
      {
        id: 2,
        name: 'PAP Received PK16',
        delivery_fee: 1000,
        other_fee: 1000,
        taxi_commission_fee: 1000,
        type: 'package',
        from_id: 1,
        amount: 10000,
        time: '10:38',
      },
      {
        id: 3,
        name: 'PAP Received PK16',
        delivery_fee: 1000,
        other_fee: 1000,
        taxi_commission_fee: 1000,
        type: 'package',
        from_id: 1,
        amount: 10000,
        time: '10:38',
      },
      {
        id: 4,
        name: 'PAP Received PK16',
        delivery_fee: 1000,
        other_fee: 1000,
        taxi_commission_fee: 1000,
        type: 'package',
        from_id: 1,
        amount: 10000,
        time: '10:38',
      },
    ],
  },
];
